pre-release-commit-message = "release: {{crate_name}} version {{version}}"
pre-release-hook = ["cargo", "make", "pre-release-hook"]
pre-release-replacements = [
  # Update html_root_url
  { file = "src/lib.rs", search = "\"https://docs.rs/[^\"]+\"", replace = "\"https://docs.rs/{{crate_name}}/{{version}}\"", prerelease = true },
  # Update dependencies usage of the form `{{crate_name}} = "{{version}}" (if present)
  { file = "src/lib.rs", search = "(?P<deps>//! \\[(dev-|build-)?dependencies\\])\n(?P<crate_name>//! \\b\\w+\\b) = \"[^\"]+\"\n", replace = "$deps\n$crate_name = \"{{version}}\"\n", min = 0, prerelease = true },
  # Update dependencies usage of the form `{{crate_name}} = { version = "{{version}}", ... } (if present)
  { file = "src/lib.rs", search = "(?P<deps>//! \\[(dev-|build-)?dependencies\\])\n(?P<crate_name>//! \\b\\w+\\b) = \\{(?P<prever>.+)(?P<ver>version = )\"[^\"]+\"(?P<postver>.+)\\}\n", replace = "$deps\n$crate_name = {${prever}version = \"{{version}}\"$postver}\n", min = 0, prerelease = true },
]
post-release-commit-message = "chore: start next iteration {{next_version}}"
tag-message = "release: {{crate_name}} version {{version}}"
dev-version-ext = "dev"

disable-push = true
disable-publish = true
